//
// Created by Tony Adriansen on 3/1/24.
//

#ifndef OPENGL_RENDERER_SRC_RENDERER_GL_STB_IMAGE_STB_IMAGE_IMPL_HPP_
#define OPENGL_RENDERER_SRC_RENDERER_GL_STB_IMAGE_STB_IMAGE_IMPL_HPP_

#define STB_IMAGE_IMPLEMENTATION
#include <dep/stb_image/stb_image.h>

#endif //OPENGL_RENDERER_SRC_RENDERER_GL_STB_IMAGE_STB_IMAGE_IMPL_HPP_
