//
// Created by Tony Adriansen on 3/1/24.
//

#ifndef OPENGL_RENDERER_SRC_RENDERER_CAMERA_ORBITCAMERA_HPP_
#define OPENGL_RENDERER_SRC_RENDERER_CAMERA_ORBITCAMERA_HPP_

class OrbitCamera {

};

#endif //OPENGL_RENDERER_SRC_RENDERER_CAMERA_ORBITCAMERA_HPP_
